<?php

return array(
    'Download your catalog' => 'Télécharger votre catalogue',
    'Footprint ID' => 'Footprint ID',
    'Get your Catalog' => 'Téléchargement de votre catalogue',
    'Module configuration' => 'Configuration du module ',
    'No footprint was generated by this order' => 'Aucun footprint PayGreen n\'a été créé pour cette commande.',
    'Operation mode' => 'Mode de fonctionnement',
    'PayGreenClimateKit Configuration' => 'Configuration du module PayGreenClimateKit',
    'Paygreen Climate Information' => 'Informations PayGreen Climate',
    'Send your Catalog' => 'Envoyer votre catalogue',
    'Send your catalog to PayGreen' => 'Envoyer votre catalogue à PayGreen',
    'Upload to PayGreen failed, please try again.' => 'L\'envoi vers PayGreen a échoué, merci de ré-essayer.',
    'You can also download your catalog and integrate it manually in the PayGreen Climate dashboard' => 'Vous pouvez télécharger votre catalogue pour l\'intégrer manuellement au tableau de bord PayGreen',
    'You can send your catalog to PayGreen to initialize your products in the Climate dashboard' => 'Vous pouvez envoyer votre catalogue de produits à PayGreen pour initialiser la liste des produits dans le tableau de bord PayGreen',
    'Your product catalog was successfully send to PayGreen.' => 'Votre catalogue de produits a bien été envoyé à PayGreen',
);
